# Generated by Django 3.2.5 on 2021-07-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('writer', 'writer'), ('reader', 'reader')], default='reader', max_length=7, null=True),
        ),
    ]
